<!DOCTYPE html>
<html>
<head>
    <title>newOffer</title>
    <link type="text/html" rel="icon" href="/images/icoMoney.ico">
</head>
<body>
<a href="/" ><img src="/images/moneyIcon64.png"> home</a> |
<a href="/interview">Собеседования</a> |
<a href="/about">о нас</a><br><br><br>
<h1>Данный портал был создан для помощи в подготовке к собеседованиям</h1><br><br>
<h2><b><a href="https://t.me/comander" target="_blank">Telegram</a></b></h2>
<h2><b><a href="https://vk.com/iloveminecraft228337" target="_blank">Vk</a></b></h2>
</body>
</html>