<!DOCTYPE html>
<html>
<head>
    <title>newOffer</title>
    <link type="text/html" rel="icon" href="images/icoMoney.ico">
</head>
<body>
<a href="/" ><img src="/images/moneyIcon64.png"> home</a> |
<a href="/interview">Собеседования</a> |
<a href="/about">о нас</a><br><br><br>
<form method="post" action="/create/language">
    Название языка: <input type="text" name="name" /><br><br>
    <input type="submit" value="Создать"/>
</form>
</body>
</html>