<!DOCTYPE html>
<html>
<head>
    <title>newOffer</title>
    <link type="text/html" rel="icon" href="/images/icoMoney.ico">
</head>
<body>
<a href="/" ><img src="/images/moneyIcon64.png"> home</a> |
<a href="/interview">Собеседования</a> |
<a href="/about">о нас</a><br><br><br>
<form method="post" action="/create/video">
    Ссылка на видео: <input type="text" name="url" /><br><br>
    Вакансия: <input type="text" name="post" /><br><br>
    Grade: <input type="text" name="grade">
    <br><br>
    К какой карточке относится: <input type="number" name="card_id" />
    <input type="submit" value="Добавить видео" />
</form>
</body>
</html>