<!DOCTYPE html>
<html>
<head>
    <title>newOffer</title>
    <link type="text/html" rel="icon" href="/images/icoMoney.ico">
</head>
<body>
    <form method="post" action="/change/card">
        id вопроса: <input type="number" name="card_id" /><br><br>
        Новое описание:<br> <textarea name="description"></textarea><br>
        <input type="submit" value="Изменить" />
    </form>
</body>
</html>